// scripts/build_nonsense_blocklist.mjs — generate data/nonsense_blocklist.js.
//
// The Crystal Lab invents "nonsense" words as onset+rime combos (engine/nonsense.js).
// makeNonsenseWord only excludes the 2,919-word game dataset, so common real words
// outside it (e.g. "leaf", "greet") leaked through and were presented as made-up
// crystals (QA I2). The set of words the generator can EVER produce is small
// (~all onset×rime combos), so rather than bundle a whole dictionary we precompute
// just the combos that are actually real English words and ship that as a blocklist.
//
// Run:  node scripts/build_nonsense_blocklist.mjs
// It fetches a comprehensive English word list (dwyl/english-words, ~370k words),
// intersects it with every producible combo across all NONSENSE_PATTERNS, and writes
// data/nonsense_blocklist.js. Re-run if ONSETS/RIMES in engine/nonsense.js change.
import { writeFile, readFile } from 'node:fs/promises';
import { ONSETS, RIMES } from '../src/engine/nonsense.js';

const DICT_URL = 'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt';
const CACHE = 'words_alpha_tmp.txt'; // local cache so reruns don't re-download

async function loadDictionary() {
  try {
    const cached = await readFile(CACHE, 'utf8');
    if (cached.length > 1_000_000) {
      console.log(`Using cached ${CACHE}`);
      return cached;
    }
  } catch {
    /* no cache */
  }
  console.log(`Fetching ${DICT_URL} ...`);
  const res = await fetch(DICT_URL);
  if (!res.ok) throw new Error(`dictionary fetch failed: ${res.status}`);
  const text = await res.text();
  await writeFile(CACHE, text);
  return text;
}

const dictText = await loadDictionary();
const dict = new Set(dictText.split(/\r?\n/).map((w) => w.trim()).filter(Boolean));
console.log(`Dictionary: ${dict.size} words`);

// Enumerate every combo the generator could produce — identical logic to
// makeNonsenseWord (onset + rime, per pattern, default ONSETS when none given).
const combos = new Set();
for (const [, entry] of Object.entries(RIMES)) {
  const onsets = entry.onsets || ONSETS;
  for (const o of onsets) for (const r of entry.rimes) combos.add(o + r);
}
console.log(`Producible combos: ${combos.size}`);

// Keep only the combos that are REAL English words — those are the leaks to block.
const blocked = [...combos].filter((w) => dict.has(w)).sort();
console.log(`Real-word combos to block: ${blocked.length}`);
console.log(`  sanity — includes "leaf": ${blocked.includes('leaf')}, "greet": ${blocked.includes('greet')}`);

const out = `// data/nonsense_blocklist.js — AUTO-GENERATED by scripts/build_nonsense_blocklist.mjs.
// Do not hand-edit. These are the onset+rime combos the Crystal Lab's nonsense
// generator can produce that are ACTUALLY real English words — so the Lab excludes
// them and never presents a real word as a made-up "crystal" (QA I2). Regenerate if
// ONSETS/RIMES in src/engine/nonsense.js change.
export const NONSENSE_BLOCKLIST = ${JSON.stringify(blocked)};
`;
await writeFile('data/nonsense_blocklist.js', out);
console.log(`Wrote data/nonsense_blocklist.js (${blocked.length} words, ${(Buffer.byteLength(out) / 1024).toFixed(1)} KB)`);
