// scripts/import_research.mjs — sample the spelling-research corpus into the app.
//
// Reads C:/Users/iango/spelling-research/app_data/ (words.jsonl ~50k forms,
// spine.json, patterns.json, homophones.json) and emits data/research_sample.js:
// the FULL spine + rules catalog, but only the top N words per (pattern x AoA band),
// picked by the app's own within-pattern order (shortest, then most frequent) — so
// the sample is exactly the words the app would teach first in each lesson.
//
// The research lists are still being processed (recall pass T4 etc.); this script
// is the repeatable import step. Re-run it against the finished corpus — with a
// bigger (or removed) cap — and the same engine (src/engine/lists.js) serves the
// full dataset unchanged.
//
// Usage: node scripts/import_research.mjs [--source <dir>] [--per-cell 2]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const arg = (name, dflt) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : dflt;
};
const SOURCE = arg('--source', 'C:/Users/iango/spelling-research/app_data');
const PER_CELL = Number(arg('--per-cell', '2'));

const readJson = (f) => JSON.parse(fs.readFileSync(path.join(SOURCE, f), 'utf8'));
const spine = readJson('spine.json');
const patternsRaw = readJson('patterns.json');
const homophonesRaw = readJson('homophones.json');

// Trim the catalog to the fields the app's reteach step uses.
const patterns = {};
for (const [id, p] of Object.entries(patternsRaw)) {
  patterns[id] = {
    id,
    label: p.label,
    rule: p.rule,
    sound: p.sound,
    graphemes: p.graphemes,
    teach_exemplars: p.teach_exemplars,
    watch: p.watch,
    category: p.category,
  };
}

// Stream words.jsonl, keeping the best PER_CELL words per (pattern, band) by the
// app's within-pattern order: length ascending, then zipf descending.
const better = (a, b) =>
  (a.length - b.length) || ((b.zipf ?? -Infinity) - (a.zipf ?? -Infinity));
const cells = new Map(); // "pattern|band" -> sorted keep-list
let total = 0;
for (const line of fs.readFileSync(path.join(SOURCE, 'words.jsonl'), 'utf8').split('\n')) {
  if (!line.trim()) continue;
  total++;
  const src = JSON.parse(line);
  const e = {
    word: src.word,
    band: src.band,
    aoa: src.aoa,
    pattern: src.pattern,
    patternIndex: src.pattern_index,
    length: src.length,
    zipf: src.zipf,
    lemma: src.lemma,
    grapheme: src.grapheme,
    homophoneId: src.homophone_id,
    sentence: src.sentence,
  };
  const k = `${e.pattern}|${e.band}`;
  const kept = cells.get(k) || [];
  kept.push(e);
  kept.sort(better);
  if (kept.length > PER_CELL) kept.length = PER_CELL;
  cells.set(k, kept);
}

const words = [...cells.values()].flat()
  .sort((a, b) => (a.patternIndex - b.patternIndex) || better(a, b));

// Keep only the homophone clusters a sampled word actually points at,
// keyed by their original index so homophoneId still resolves.
const homophones = {};
for (const e of words) {
  if (e.homophoneId != null && homophonesRaw[e.homophoneId]) {
    homophones[e.homophoneId] = homophonesRaw[e.homophoneId];
  }
}

const out = {
  source: 'spelling-research/app_data (see RESEARCH_INTEGRATION.md)',
  samplePerPatternBand: PER_CELL,
  corpusWords: total,
  spine,
  patterns,
  homophones,
  words,
};

const banner = `// data/research_sample.js — GENERATED by scripts/import_research.mjs. Do not edit.
// A ${PER_CELL}-per-(pattern x band) sample of the spelling-research corpus
// (${total} forms at import time). Consumed by src/engine/lists.js; not yet in the
// live game path, build_deploy, or the sw precache. Re-run the importer to refresh.
`;
const file = path.join(ROOT, 'data', 'research_sample.js');
fs.writeFileSync(file, `${banner}export const RESEARCH = ${JSON.stringify(out, null, 1)};\n`);

const bands = new Set(words.map((e) => e.band));
const lessons = new Set(words.map((e) => e.pattern));
console.log(`corpus: ${total} forms -> sample: ${words.length} words`);
console.log(`lessons covered: ${lessons.size}/${spine.length}  bands: ${bands.size}  homophone clusters: ${Object.keys(homophones).length}`);
console.log(`wrote ${file} (${(fs.statSync(file).size / 1024).toFixed(0)} KB)`);
