// scripts/merge.mjs — assemble the final engine dataset (data/words.js) from:
//   - data/patterns.js  : canonical spelling-pattern families (re-exported)
//   - data/chunks/part_*.js : the 12 enriched chunks (authoritative frequency ranks)
//   - data/curated.js   : the 317 hand-crafted entries, layered on top as a quality overlay
// Drops skip:true entries, dedups, validates, sorts by frequency (rank asc), writes data/words.js.
import { writeFile } from 'node:fs/promises';
import { PATTERNS, PATTERN_IDS } from '../data/patterns.js';

const NCHUNKS = 12;
const FIELDS = ['word', 'rank', 'tier', 'pattern', 'syllables', 'misspellings', 'sentence'];

function norm(w) {
  return {
    word: String(w.word).toLowerCase(),
    rank: w.rank,
    tier: w.tier,
    pattern: w.pattern,
    syllables: Array.isArray(w.syllables) ? w.syllables : [String(w.word)],
    misspellings: Array.isArray(w.misspellings) ? w.misspellings.filter((m) => m && m !== w.word) : [],
    sentence: w.sentence || '',
  };
}
const uniq = (arr) => [...new Set(arr)];

// --- load enriched chunks (authoritative ranks) ---
const map = new Map();
let skipCount = 0, chunkTotal = 0;
for (let c = 0; c < NCHUNKS; c++) {
  const id = String(c).padStart(2, '0');
  const mod = await import(`../data/chunks/part_${id}.js`);
  for (const w of mod.WORDS) {
    chunkTotal++;
    if (w.skip) { skipCount++; continue; }
    map.set(String(w.word).toLowerCase(), norm(w));
  }
}

// --- layer the curated overlay on top (better sentences + hand-picked misspellings) ---
const { WORDS: CURATED } = await import('../data/curated.js');
let mergedCount = 0, curatedOnly = 0;
for (const c of CURATED) {
  const word = String(c.word).toLowerCase();
  if (map.has(word)) {
    const e = map.get(word);
    map.set(word, {
      word,
      rank: e.rank, // keep the authoritative backbone frequency rank
      tier: c.tier,
      pattern: c.pattern,
      syllables: c.syllables,
      misspellings: uniq([...(c.misspellings || []), ...e.misspellings]).filter((m) => m && m !== word),
      sentence: c.sentence || e.sentence,
    });
    mergedCount++;
  } else {
    map.set(word, norm(c)); // curated word outside the top-3000 backbone — keep its own rank
    curatedOnly++;
  }
}

// --- validate ---
const all = [...map.values()];
const problems = [];
for (const w of all) {
  if (!PATTERN_IDS.has(w.pattern)) problems.push(`bad pattern ${w.word}:${w.pattern}`);
  if (w.syllables.join('') !== w.word) problems.push(`bad syllables ${w.word}:${w.syllables.join('-')}`);
  if (w.misspellings.includes(w.word)) problems.push(`misspelling==word ${w.word}`);
  if (typeof w.rank !== 'number') problems.push(`bad rank ${w.word}`);
  if (typeof w.tier !== 'number' || w.tier < 1 || w.tier > 9) problems.push(`bad tier ${w.word}:${w.tier}`);
}
if (problems.length) {
  console.error('VALIDATION PROBLEMS:', problems.length);
  console.error(problems.slice(0, 25).join('\n'));
  process.exit(1);
}

// --- sort by frequency (rank asc), stable tiebreak by word ---
all.sort((a, b) => a.rank - b.rank || (a.word < b.word ? -1 : 1));

// --- write data/words.js ---
const lines = all.map((w) => '  ' + JSON.stringify(w, FIELDS)).join(',\n');
const out =
  `// data/words.js — AUTO-GENERATED by scripts/merge.mjs. Do not edit by hand.\n` +
  `// ${all.length} words, frequency-ordered (rank 1 = most common). Spans ages 5-13.\n` +
  `// Rebuild: node scripts/merge.mjs\n` +
  `import { PATTERNS } from './patterns.js';\n` +
  `export { PATTERNS };\n` +
  `export const WORDS = [\n${lines}\n];\n`;
await writeFile('data/words.js', out);

// --- report ---
const byTier = {}, byPattern = {};
for (const w of all) { byTier[w.tier] = (byTier[w.tier] || 0) + 1; byPattern[w.pattern] = (byPattern[w.pattern] || 0) + 1; }
console.log('chunkTotal', chunkTotal, 'skipped', skipCount, 'curatedMerged', mergedCount, 'curatedOnly', curatedOnly);
console.log('FINAL WORDS', all.length, 'patterns', PATTERNS.length);
console.log('per-tier:', JSON.stringify(byTier));
const patternCounts = Object.entries(byPattern).sort((a, b) => b[1] - a[1]);
console.log('top patterns:', patternCounts.slice(0, 12).map(([k, v]) => `${k}:${v}`).join(' '));
console.log('thin patterns (<8):', patternCounts.filter(([, v]) => v < 8).map(([k, v]) => `${k}:${v}`).join(' ') || 'none');
console.log('first 12:', all.slice(0, 12).map((w) => w.word).join(' '));
